name: Container

on:
  workflow_call:
    outputs:
      container-tag:
        value: ${{ jobs.necessary.outputs.container-tag }}

jobs:
  necessary:
    name: Necessary?
    runs-on: ["self-hosted", "X64"]
    outputs:
      build: ${{ steps.changed-files.outputs.all_changed_and_modified_files != '' }}
      container-tag: ${{ steps.container-tag.outputs.tag }}

    steps:
      - name: Clean workspace
        run: |
          git clean -ffdx || true
          git reset --hard || true
          git submodule foreach --recursive git clean -ffdx || true
          git submodule foreach --recursive git reset --hard || true
          git submodule deinit --all -f || true
        continue-on-error: true

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: tj-actions/changed-files@24d32ffd492484c1d75e0c0b894501ddb9d30d62 # v47
        id: changed-files
        with:
          exclude_submodules: true
          files: |
            .devcontainer/Dockerfile

      - name: Set container tag
        id: container-tag
        run: |
          if [[ "${{ steps.changed-files.outputs.all_changed_and_modified_files }}" != "" && "${{ github.ref }}" != "refs/heads/master" ]]; then
            tag="${{ github.sha }}"
          else
            tag="latest"
          fi
          echo "tag=$tag" >> $GITHUB_OUTPUT

  build-push:
    name: Build and push
    if: needs.necessary.outputs.build == 'true'
    needs:
      - necessary
    timeout-minutes: 360
    strategy:
      matrix:
        include:
          - platform: "amd64"
            runner: ["self-hosted", "X64"]
          - platform: "arm64"
            runner: ["self-hosted", "ARM64"]
    runs-on: ${{ matrix.runner }}

    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Github Registry
        uses: docker/login-action@v3
        with:
          username: ${{ github.actor }}
          password: ${{ github.token }}
          registry: ghcr.io

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .devcontainer
          file: .devcontainer/Dockerfile
          target: atym-base
          provenance: false
          push: true
          tags: ghcr.io/${{ github.repository }}/atym-toolchain:${{ needs.necessary.outputs.container-tag }}-${{ matrix.platform }}

  manifest:
    if: needs.necessary.outputs.build == 'true'
    needs:
      - necessary
      - build-push
    name: Docker manifest
    runs-on: ["self-hosted", "X64"]

    steps:
      - name: Login to Github Registry
        uses: docker/login-action@v3
        with:
          username: ${{ github.actor }}
          password: ${{ github.token }}
          registry: ghcr.io

      - name: Create and push multiarch manifests
        run: |
          docker manifest rm ghcr.io/${{ github.repository }}/atym-toolchain:${{ needs.necessary.outputs.container-tag }} || true
          docker manifest create \
            ghcr.io/${{ github.repository }}/atym-toolchain:${{ needs.necessary.outputs.container-tag }} \
            ghcr.io/${{ github.repository }}/atym-toolchain:${{ needs.necessary.outputs.container-tag }}-amd64 \
            ghcr.io/${{ github.repository }}/atym-toolchain:${{ needs.necessary.outputs.container-tag }}-arm64
          docker manifest push ghcr.io/${{ github.repository }}/atym-toolchain:${{ needs.necessary.outputs.container-tag }}
